version: '3'

services:
  node1:
    image: cassandra:latest
    container_name: cassandra-node1
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=node1,node2,node3"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_RACK=rack1"
    restart: always
    volumes:
      - ./data/node1:/var/lib/cassandra
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  node2:
    image: cassandra:latest
    container_name: cassandra-node2
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=node1,node2,node3"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_RACK=rack2"
    restart: always
    volumes:
      - ./data/node2:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  node3:
    image: cassandra:latest
    container_name: cassandra-node3
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=node1,node2,node3"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_RACK=rack3"
    restart: always
    volumes:
      - ./data/node3:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:latest
    depends_on:
      node1:
        condition: service_healthy
      node2:
        condition: service_healthy
      node3:
        condition: service_healthy
    volumes:
      - ./init-scripts/01-keyspace.cql:/docker-entrypoint-initdb.d/01-keyspace.cql
      - ./init-scripts/load-keyspace.sh:/docker-entrypoint-initdb.d/load-keyspace.sh
    command: /bin/bash -c "/docker-entrypoint-initdb.d/load-keyspace.sh"