version: '3'
services:
  cassandra1:
    image: cassandra
    container_name: cassandra1
    hostname: cassandra1
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3"
      - "CASSANDRA_CLUSTER_NAME=Cluster final"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_RACK=rack1"
      - "CASSANDRA_PASSWORD=qwert"
    restart: always
    volumes:
      - ./data/cassandra1:/var/lib/cassandra
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "cqlsh", "-u admin", "-p qwert" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra2:
    image: cassandra
    container_name: cassandra2
    hostname: cassandra2
    ports:
      - "9043:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3"
      - "CASSANDRA_CLUSTER_NAME=Cluster final"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_RACK=rack2"
      - "CASSANDRA_PASSWORD=qwert"
    restart: always
    volumes:
      - ./data/cassandra2:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra3:
    image: cassandra
    container_name: cassandra3
    hostname: cassandra3
    ports:
      - "9044:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3"
      - "CASSANDRA_CLUSTER_NAME=Cluster final"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_RACK=rack3"
      - "CASSANDRA_PASSWORD=qwert"
    restart: always
    volumes:
      - ./data/cassandra3:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:latest
    depends_on:
      cassandra1:
        condition: service_healthy
      cassandra2:
        condition: service_healthy
      cassandra3:
        condition: service_healthy
    volumes:
      - ./init-scripts/01-keyspace.cql:/docker-entrypoint-initdb.d/01-keyspace.cql
      - ./init-scripts/load-keyspace.sh:/docker-entrypoint-initdb.d/load-keyspace.sh
    command: /bin/bash -c "/docker-entrypoint-initdb.d/load-keyspace.sh"